### PR TITLE
Fix for a compile error in code snippet from chapter 7 - 7.2.1 Traver…

### PR DESCRIPTION
**Pull request by deniszjukow**
…sing with Futures

### CODE REVIEW

**Comment by deniszjukow** [comment]
Accumulator should have type Future[List[B]] (same as the return value)

**Review by davegurnell — APPROVED** [review]
Thank you — good spot! Please add yourself to contributors.md if you haven’t already!

**Comment by deniszjukow** [comment]
One more really small correction in chapter 7. I've also added myself to contributors.md. Thank you!

**Comment by davegurnell** [comment]
Thanks again!

**Pull request merged**
